<?php
/**
 * Definições da tabela saude_TESTADORES
 */
$dictionary['saude_TESTADORES'] = array(
    'table' => 'saude_testadores_conexoes',
    'schema_version' => 'v1.0.0',
    'reportable' => false,
    'duplicate_check' => false,
    'unified_search' => false,
    'fields' => array(
        'id' => array(
            'name' => 'id',
            'vname' => 'LBL_ID',
            'type' => 'id',
            'required' => true,
            'reportable' => true,
        ),
        'data_hora_login' => array(
            'name' => 'data_hora_login',
            'vname' => 'LBL_DATA_HORA_LOGIN',
            'type' => 'datetime',
            'required' => true,
            'reportable' => true,
        ),
        'data_hora_logout' => array(
            'name' => 'data_hora_logout',
            'vname' => 'LBL_DATA_HORA_LOGOUT',
            'type' => 'datetime',
            'required' => false,
            'reportable' => true,
        ),
        'tempo_conectado_segundos' => array(
            'name' => 'tempo_conectado_segundos',
            'vname' => 'LBL_TEMPO_CONECTADO',
            'type' => 'int',
            'required' => false,
            'reportable' => true,
        ),
        'usuario_id' => array(
            'name' => 'usuario_id',
            'vname' => 'LBL_USUARIO_ID',
            'type' => 'id',
            'required' => false,
            'reportable' => true,
        ),
        'usuario_nome' => array(
            'name' => 'usuario_nome',
            'vname' => 'LBL_USUARIO_NOME',
            'type' => 'varchar',
            'len' => 100,
            'required' => false,
            'reportable' => true,
        ),
        'usuario_email' => array(
            'name' => 'usuario_email',
            'vname' => 'LBL_USUARIO_EMAIL',
            'type' => 'varchar',
            'len' => 150,
            'required' => false,
            'reportable' => true,
        ),
        'usuario_login' => array(
            'name' => 'usuario_login',
            'vname' => 'LBL_USUARIO_LOGIN',
            'type' => 'varchar',
            'len' => 50,
            'required' => false,
            'reportable' => true,
        ),
        'ip_address' => array(
            'name' => 'ip_address',
            'vname' => 'LBL_IP_ADDRESS',
            'type' => 'varchar',
            'len' => 45,
            'required' => false,
            'reportable' => true,
        ),
        'navegador' => array(
            'name' => 'navegador',
            'vname' => 'LBL_NAVEGADOR',
            'type' => 'varchar',
            'len' => 100,
            'required' => false,
            'reportable' => true,
        ),
        'ambiente' => array(
            'name' => 'ambiente',
            'vname' => 'LBL_AMBIENTE',
            'type' => 'varchar',
            'len' => 50,
            'required' => false,
            'reportable' => true,
        ),
        'sessao_id' => array(
            'name' => 'sessao_id',
            'vname' => 'LBL_SESSAO_ID',
            'type' => 'varchar',
            'len' => 100,
            'required' => false,
            'reportable' => true,
        ),
        'status' => array(
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'options' => 'status_testador_list',
            'required' => true,
            'reportable' => true,
            'default' => 'OFFLINE',
        ),
        'data_hora_status' => array(
            'name' => 'data_hora_status',
            'vname' => 'LBL_DATA_HORA_STATUS',
            'type' => 'datetime',
            'required' => true,
            'reportable' => true,
        ),
        'criado_em' => array(
            'name' => 'criado_em',
            'vname' => 'LBL_CRIADO_EM',
            'type' => 'datetime',
            'required' => false,
            'reportable' => true,
            'default' => 'CURRENT_TIMESTAMP',
        ),
        'modificado_em' => array(
            'name' => 'modificado_em',
            'vname' => 'LBL_MODIFICADO_EM',
            'type' => 'datetime',
            'required' => false,
            'reportable' => true,
            'default' => 'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
        ),
        // Campos do SugarCRM para relacionamento
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'dbType' => 'varchar',
            'len' => 255,
            'unified_search' => true,
            'full_text_search' => array('boost' => 3),
            'importable' => 'required',
            'required' => true,
        ),
    ),
    'indices' => array(
        array('name' => 'saude_testadores_conexoespk', 'type' => 'primary', 'fields' => array('id')),
        array('name' => 'idx_status', 'type' => 'index', 'fields' => array('status')),
        array('name' => 'idx_usuario_id', 'type' => 'index', 'fields' => array('usuario_id')),
        array('name' => 'idx_login_logout', 'type' => 'index', 'fields' => array('data_hora_login', 'data_hora_logout')),
        array('name' => 'idx_data_hora_status', 'type' => 'index', 'fields' => array('data_hora_status')),
        array('name' => 'idx_sessao_id', 'type' => 'index', 'fields' => array('sessao_id')),
    ),
    'relationships' => array(
    ),
);